function PARAM = Calc_Anisotropy_FacetAngular(STATE,PARAM,GRID,PHYS,MODEL)
%CALC_ANISOTROPY_FACETANGULAR Faceted anisotropy with angular-flux term.
%
% This implements the scalar variational anisotropic AC form:
%
%   phi_t = div( LK(theta)*grad(phi) ) + div(Ftheta)
%           - Lm(theta)*W'(phi) - L_chem*Q
%
% where LK(theta) and Lm(theta) are scaled by the Kundin surface-energy
% factor S_sigma, and the angular derivative term div(Ftheta) is computed
% explicitly from the old phase field.
%
% Default behavior:
%   - scale LK_AC and Lm_AC by S_sigma
%   - keep L_AC unscaled, so chemical driving force is not facet-scaled
%   - store explicit angular term in PARAM.DivAnisoAngular_AC
%
% Optional:
%   PARAM.aniso_scale_chemical = 1  also scales L_AC by S_sigma
%                                this is kinetic anisotropy / legacy mode
%
% Notes:
%   - facet theta from metadata is in degrees if theta_deg exists.
%   - PARAM.theta_grain is assumed to be in radians, as generated by map code.
%   - MODEL is optional. If provided, PARAM.facet is read by thermodynamic
%     phase index MODEL.phase_index(ig). Otherwise grain index is used.

if nargin < 5
    MODEL = [];
end

phi        = STATE.phi;
[ny,nx,Np] = size(phi);

dx = GRID.dx;
dy = GRID.dy;

% ------------------------------------------------------------
% Defaults
% ------------------------------------------------------------
g_rel   = 0.02;
phi_cut = 1e-3;

if isfield(PARAM,'aniso_g_rel'),   g_rel   = PARAM.aniso_g_rel;   end
if isfield(PARAM,'aniso_phi_cut'), phi_cut = PARAM.aniso_phi_cut; end

scale_chemical = 0;
if isfield(PARAM,'aniso_scale_chemical')
    scale_chemical = PARAM.aniso_scale_chemical;
end

% Regularization for dtheta/dgrad(phi)
if isfield(PARAM,'aniso_grad_eps')
    eps_g = PARAM.aniso_grad_eps;
else
    if isfield(PHYS,'l') && PHYS.l > 0
        eps_g = (1e-3/PHYS.l)^2;
    else
        eps_g = 1e-12;
    end
end

% Grain rotations are stored in radians in map generation.
theta_grain = zeros(1,Np);
if isfield(PARAM,'theta_grain')
    ncopy = min(Np,numel(PARAM.theta_grain));
    theta_grain(1:ncopy) = PARAM.theta_grain(1:ncopy);
end

% ------------------------------------------------------------
% Allocate diagnostic/output fields
% ------------------------------------------------------------
PARAM.aniso_phix        = zeros(ny,nx,Np);
PARAM.aniso_phiy        = zeros(ny,nx,Np);
PARAM.aniso_gmag        = zeros(ny,nx,Np);
PARAM.aniso_theta       = zeros(ny,nx,Np);  % degrees, lab frame
PARAM.aniso_theta_diff  = zeros(ny,nx,Np);  % degrees to nearest facet
PARAM.aniso_facet_id    = zeros(ny,nx,Np);
PARAM.aniso_facet_A     = ones(ny,nx,Np);
PARAM.aniso_S           = ones(ny,nx,Np);
PARAM.aniso_dS_dtheta   = zeros(ny,nx,Np);  % derivative wrt radians
PARAM.aniso_mask        = false(ny,nx,Np);

PARAM.LK_iso            = zeros(ny,nx,Np);
PARAM.Lm_iso            = zeros(ny,nx,Np);
PARAM.LK_AC             = zeros(ny,nx,Np);
PARAM.Lm_AC             = zeros(ny,nx,Np);
PARAM.L_AC              = zeros(ny,nx,Np);
PARAM.m_AC_base         = zeros(ny,nx,Np);
PARAM.DivAnisoAngular_AC = zeros(ny,nx,Np);

% ------------------------------------------------------------
% Loop over grains/order parameters
% ------------------------------------------------------------
for ig = 1:Np

    ph = phi(:,:,ig);

    [phix,phiy] = Grad2D_Reflect(ph,dx,dy);

    g2_noeps = phix.^2 + phiy.^2;
    gmag     = sqrt(g2_noeps);

    theta_lab_deg = mod(atan2d(phiy,phix),360);

    PARAM.aniso_phix(:,:,ig)  = phix;
    PARAM.aniso_phiy(:,:,ig)  = phiy;
    PARAM.aniso_gmag(:,:,ig)  = gmag;
    PARAM.aniso_theta(:,:,ig) = theta_lab_deg;

    % Base coefficients
    Lloc   = Get_Field(PARAM.L,ig,ny,nx);
    kaploc = Get_Field(PHYS.kap,ig,ny,nx);
    mloc   = Get_Field(PHYS.m,ig,ny,nx);

    LK0 = Lloc .* kaploc;
    Lm0 = Lloc .* mloc;

    S          = ones(ny,nx);
    dS_dtheta  = zeros(ny,nx);
    ifacet_map = zeros(ny,nx);
    A_map      = ones(ny,nx);
    dth_degmap = zeros(ny,nx);

    % Which PARAM.facet entry should this grain use?
    iph = ig;
    if ~isempty(MODEL) && isfield(MODEL,'phase_index') && numel(MODEL.phase_index) >= ig
        iph = MODEL.phase_index(ig);
    end

    has_facet = isfield(PARAM,'facet') && numel(PARAM.facet) >= iph;

    if has_facet

        facet = PARAM.facet(iph);

        mode = 'iso';
        if isfield(facet,'mode') && ~isempty(facet.mode)
            mode = facet.mode;
        elseif isfield(PARAM,'aniso_phase') && any(iph == PARAM.aniso_phase)
            mode = 'facet';
        end

        if ~strcmpi(mode,'iso')

            [facet_theta_deg,facet_A,A_ref,q,amin,amax] = Local_Get_Facet_Data(facet,PARAM);

            if ~isempty(facet_theta_deg)

                % Convert lab-frame normal angle to crystal frame.
                % theta_grain is radians, convert to degrees.
                theta_crystal_deg = mod(theta_lab_deg - rad2deg(theta_grain(ig)),360);

                [dth_deg,ifacet] = NearestFacetDeg(theta_crystal_deg,facet_theta_deg);

                A_use = facet_A(ifacet);

                dth_rad = dth_deg*pi/180;

                den = sin(dth_rad).^2 + q^2*cos(dth_rad).^2;
                den = max(den,eps);

                % Kundin surface-energy factor:
                % S_sigma = (A_ref/A_use)*sqrt(den)/q
                S_raw = (A_ref ./ max(A_use,eps)) .* sqrt(den) ./ max(q,eps);

                % dS_sigma/dtheta, derivative wrt radians
                dS_raw = (A_ref ./ max(A_use,eps)) .* (1 - q^2) .* ...
                    sin(dth_rad).*cos(dth_rad) ./ (max(q,eps).*sqrt(den));

                % Limits are useful for numerical stability
                S_raw = max(S_raw,amin);
                S_raw = min(S_raw,amax);

                % Interface mask
                gmax = max(gmag,[],'all');
                if gmax > 0
                    mask_g = gmag > g_rel*gmax;
                else
                    mask_g = false(ny,nx);
                end

                mask_phi = ph > phi_cut & ph < 1 - phi_cut;
                mask = mask_g | mask_phi;

                S(mask)         = S_raw(mask);
                dS_dtheta(mask) = dS_raw(mask);

                ifacet_map(mask) = ifacet(mask);
                A_map(mask)      = A_use(mask);
                dth_degmap(mask) = dth_deg(mask);

            else
                mask = false(ny,nx);
            end

        else
            mask = false(ny,nx);
        end

    else
        mask = false(ny,nx);
    end

    % Coefficients for scalar AC solver
    PARAM.LK_iso(:,:,ig)    = LK0;
    PARAM.Lm_iso(:,:,ig)    = Lm0;
    PARAM.LK_AC(:,:,ig)     = LK0 .* S;
    PARAM.Lm_AC(:,:,ig)     = Lm0 .* S;
    PARAM.m_AC_base(:,:,ig) = mloc;

    if scale_chemical == 1
        PARAM.L_AC(:,:,ig) = Lloc .* S;
    else
        PARAM.L_AC(:,:,ig) = Lloc;
    end

    % Angular flux term in combined coefficient notation
    LK_theta = LK0 .* dS_dtheta;
    Lm_theta = Lm0 .* dS_dtheta;

    W = ph.^2 .* (1 - ph).^2;

    B = 0.5 .* LK_theta .* g2_noeps + Lm_theta .* W;

    g2 = g2_noeps + eps_g;

    Fx = -B .* phiy ./ g2;
    Fy =  B .* phix ./ g2;

    DivAngular = Div2D_Reflect(Fx,Fy,dx,dy);
    DivAngular(~mask) = 0;

    PARAM.DivAnisoAngular_AC(:,:,ig) = DivAngular;

    % Diagnostics
    PARAM.aniso_theta_diff(:,:,ig) = dth_degmap;
    PARAM.aniso_facet_id(:,:,ig)   = ifacet_map;
    PARAM.aniso_facet_A(:,:,ig)    = A_map;
    PARAM.aniso_S(:,:,ig)          = S;
    PARAM.aniso_dS_dtheta(:,:,ig)  = dS_dtheta;
    PARAM.aniso_mask(:,:,ig)       = mask;

end

end


%% ========================================================================
%  Local helper functions
% ========================================================================
function F = Get_Field(A,ip,ny,nx)

if isscalar(A)
    F = A*ones(ny,nx);
elseif ndims(A) == 2 && isequal(size(A),[ny nx])
    F = A;
elseif ndims(A) == 3
    F = A(:,:,min(ip,size(A,3)));
elseif isvector(A)
    F = A(min(ip,numel(A))) * ones(ny,nx);
else
    F = A(1)*ones(ny,nx);
end

end


function [facet_theta_deg,facet_A,A_ref,q,amin,amax] = Local_Get_Facet_Data(facet,PARAM)

facet_theta_deg = [];
facet_A         = [];

if isfield(facet,'theta_deg') && ~isempty(facet.theta_deg)
    facet_theta_deg = facet.theta_deg(:);
elseif isfield(facet,'theta') && ~isempty(facet.theta)
    facet_theta_deg = facet.theta(:)*180/pi;
end

if isfield(facet,'A') && ~isempty(facet.A)
    facet_A = facet.A(:);
elseif isfield(facet,'A_weight') && ~isempty(facet.A_weight)
    facet_A = facet.A_weight(:);
else
    facet_A = ones(size(facet_theta_deg));
end

if isempty(facet_A) && ~isempty(facet_theta_deg)
    facet_A = ones(size(facet_theta_deg));
end

if numel(facet_A) ~= numel(facet_theta_deg)
    error('Facet theta and A arrays must have the same length.')
end

if isfield(facet,'A_ref') && ~isempty(facet.A_ref)
    A_ref = facet.A_ref;
elseif ~isempty(facet_A)
    A_ref = max(facet_A);
else
    A_ref = 1.0;
end

if isfield(facet,'q') && ~isempty(facet.q)
    q = facet.q;
elseif isfield(PARAM,'aniso_q')
    q = PARAM.aniso_q;
else
    q = 0.25;
end

if isfield(facet,'amin') && ~isempty(facet.amin)
    amin = facet.amin;
elseif isfield(PARAM,'aniso_min')
    amin = PARAM.aniso_min;
else
    amin = 0.2;
end

if isfield(facet,'amax') && ~isempty(facet.amax)
    amax = facet.amax;
elseif isfield(PARAM,'aniso_max')
    amax = PARAM.aniso_max;
else
    amax = 5.0;
end

facet_A = max(facet_A,eps);
A_ref   = max(A_ref,eps);
q       = max(q,eps);

end


function [dth_best,ifacet_best] = NearestFacetDeg(theta_deg,facet_theta_deg)

[ny,nx] = size(theta_deg);
Nfacet  = numel(facet_theta_deg);

% Add opposite normals, but treat planes as unoriented.
facet_all = [facet_theta_deg(:); facet_theta_deg(:)+180];

abs_best    = inf(ny,nx);
dth_best    = zeros(ny,nx);
ifacet_best = ones(ny,nx);

for k = 1:numel(facet_all)

    d_signed = AngleDiffSignedHalfDeg(theta_deg,facet_all(k));
    take     = abs(d_signed) < abs_best;

    abs_best(take) = abs(d_signed(take));
    dth_best(take) = d_signed(take);

    kk = mod(k-1,Nfacet) + 1;
    ifacet_best(take) = kk;

end

end


function d = AngleDiffSignedHalfDeg(theta1,theta2)
% Signed angular difference for plane normals, in [-90,90] degrees.

d = mod(theta1 - theta2 + 90,180) - 90;

end


function [fx,fy] = Grad2D_Reflect(f,dx,dy)

[ny,nx] = size(f);

fx = zeros(ny,nx);
fy = zeros(ny,nx);

if nx == 1
    fx(:) = 0;
else
    fx(:,2:nx-1) = (f(:,3:nx) - f(:,1:nx-2))/(2*dx);
    fx(:,1)      = (f(:,2) - f(:,1))/dx;
    fx(:,nx)     = (f(:,nx) - f(:,nx-1))/dx;
end

if ny == 1
    fy(:) = 0;
else
    fy(2:ny-1,:) = (f(3:ny,:) - f(1:ny-2,:))/(2*dy);
    fy(1,:)      = (f(2,:) - f(1,:))/dy;
    fy(ny,:)     = (f(ny,:) - f(ny-1,:))/dy;
end

end


function divF = Div2D_Reflect(Fx,Fy,dx,dy)

[dFxdx,~] = Grad2D_Reflect(Fx,dx,dy);
[~,dFydy] = Grad2D_Reflect(Fy,dx,dy);

divF = dFxdx + dFydy;

end
