function PARAM = Calc_AC_Anisotropy_Simple(STATE,PARAM,GRID)
%CALC_AC_ANISOTROPY_SIMPLE Simple orientation-dependent AC interface energy.
%
% This version preserves the heterogeneous base fields generated by
% Compute_M_And_L. It scales only Lm_AC and LK_AC; L_AC remains unchanged.
%
% Required preferred inputs:
%   PARAM.L_AC_base
%   PARAM.Lm_AC_base
%   PARAM.LK_AC_base
%
% Backward-compatible fallbacks:
%   PARAM.L
%   PARAM.Lm
%   PARAM.LK

[ny,nx,Ngrain] = size(STATE.phi);

delta    = 0.03;
nfold    = 4;
grad_min = 1e-12;

if isfield(PARAM,'aniso_delta'),    delta    = PARAM.aniso_delta;    end
if isfield(PARAM,'aniso_nfold'),    nfold    = PARAM.aniso_nfold;    end
if isfield(PARAM,'aniso_grad_min'), grad_min = PARAM.aniso_grad_min; end

theta0 = zeros(1,Ngrain);

if isfield(PARAM,'theta_grain')
    ncopy = min(numel(PARAM.theta_grain),Ngrain);
    theta0(1:ncopy) = PARAM.theta_grain(1:ncopy);
end

L_base  = Local_Resolve_Base(PARAM,'L_AC_base','L',Ngrain,ny,nx);
Lm_base = Local_Resolve_Base(PARAM,'Lm_AC_base','Lm',Ngrain,ny,nx);
LK_base = Local_Resolve_Base(PARAM,'LK_AC_base','LK',Ngrain,ny,nx);

PARAM.L_AC  = L_base;
PARAM.Lm_AC = Lm_base;
PARAM.LK_AC = LK_base;

for alpha = 1:Ngrain

    phi = STATE.phi(:,:,alpha);

    if nx == 1
        phi_L = phi;
        phi_R = phi;
    else
        phi_L = phi(:,[2,1:nx-1]);
        phi_R = phi(:,[2:nx,nx-1]);
    end

    if ny == 1
        phi_U = phi;
        phi_D = phi;
    else
        phi_U = phi([2,1:ny-1],:);
        phi_D = phi([2:ny,ny-1],:);
    end

    gx = (phi_R - phi_L)/(2*GRID.dx);
    gy = (phi_D - phi_U)/(2*GRID.dy);

    gnorm = sqrt(gx.^2 + gy.^2);
    theta = atan2(gy,gx) - theta0(alpha);

    a = 1 + delta*cos(nfold*theta);
    a = max(a,0.2);

    % Orientation is undefined in phase interiors.
    a(gnorm < grad_min) = 1;

    PARAM.L_AC(:,:,alpha)  = L_base(:,:,alpha);
    PARAM.Lm_AC(:,:,alpha) = Lm_base(:,:,alpha) .* a;
    PARAM.LK_AC(:,:,alpha) = LK_base(:,:,alpha) .* a;

end

end


function F3 = Local_Resolve_Base(PARAM,preferred_name,fallback_name,Ngrain,ny,nx)

if isfield(PARAM,preferred_name) && ~isempty(PARAM.(preferred_name))
    A = PARAM.(preferred_name);
elseif isfield(PARAM,fallback_name) && ~isempty(PARAM.(fallback_name))
    A = PARAM.(fallback_name);
else
    error('Calc_AC_Anisotropy_Simple: missing %s or %s.', ...
          preferred_name,fallback_name)
end

if isscalar(A)

    F3 = repmat(A,ny,nx,Ngrain);

elseif ndims(A) == 2 && isequal(size(A),[ny nx])

    F3 = repmat(A,1,1,Ngrain);

elseif ndims(A) == 3 && size(A,1) == ny && size(A,2) == nx && ...
        size(A,3) >= Ngrain

    F3 = A(:,:,1:Ngrain);

else

    error(['Calc_AC_Anisotropy_Simple: field %s/%s has an ', ...
           'incompatible size.'],preferred_name,fallback_name)

end

end
