function PARAM = Calc_AC_Anisotropy_FacetedStiffness(STATE,PARAM,MODEL,GRID)
%CALC_AC_ANISOTROPY_FACETEDSTIFFNESS Kundin-style faceted AC anisotropy.
%
% This version preserves the heterogeneous, phase/grain-dependent base
% fields generated by Compute_M_And_L:
%
%   PARAM.L_AC_base(:,:,ig)
%   PARAM.Lm_AC_base(:,:,ig)
%   PARAM.LK_AC_base(:,:,ig)
%
% The anisotropy factor scales only the barrier and gradient/interface
% terms. The chemical mobility L_AC is not anisotropy-scaled.
%
% Outputs used by Calc_S_AllenCahn and the ACCH solver:
%
%   PARAM.L_AC(:,:,ig)
%   PARAM.Lm_AC(:,:,ig)
%   PARAM.LK_AC(:,:,ig)

[ny,nx,Ngrain] = size(STATE.phi);

if ~isfield(MODEL,'phase_index') || numel(MODEL.phase_index) ~= Ngrain
    error(['Calc_AC_Anisotropy_FacetedStiffness: MODEL.phase_index ', ...
           'must have one entry per grain.'])
end

% -------------------------------------------------------------------------
% Defaults
% -------------------------------------------------------------------------
nfold       = 4;
q_default   = 0.25;
s_min       = 0.1;
s_max       = 20.0;
grad_min    = 1e-12;
p_cut       = 1e-8;
normalize_s = 0;
rsl         = 1.0;

if isfield(PARAM,'aniso_nfold'),       nfold       = PARAM.aniso_nfold;       end
if isfield(PARAM,'aniso_q'),           q_default   = PARAM.aniso_q;           end
if isfield(PARAM,'aniso_min'),         s_min       = PARAM.aniso_min;         end
if isfield(PARAM,'aniso_max'),         s_max       = PARAM.aniso_max;         end
if isfield(PARAM,'aniso_grad_min'),    grad_min    = PARAM.aniso_grad_min;    end
if isfield(PARAM,'aniso_p_cut'),       p_cut       = PARAM.aniso_p_cut;       end
if isfield(PARAM,'aniso_normalize'),   normalize_s = PARAM.aniso_normalize;   end
if isfield(PARAM,'aniso_rsl'),         rsl         = PARAM.aniso_rsl;         end

% Resolve immutable base fields. Never use the already anisotropy-scaled
% PARAM.Lm_AC/PARAM.LK_AC as input, otherwise repeated calls compound factors.
L_base  = Local_Resolve_Base(PARAM,'L_AC_base','L',Ngrain,ny,nx);
Lm_base = Local_Resolve_Base(PARAM,'Lm_AC_base','Lm',Ngrain,ny,nx);
LK_base = Local_Resolve_Base(PARAM,'LK_AC_base','LK',Ngrain,ny,nx);

theta_grain = zeros(1,Ngrain);

if isfield(PARAM,'theta_grain')
    ncopy = min(numel(PARAM.theta_grain),Ngrain);
    theta_grain(1:ncopy) = PARAM.theta_grain(1:ncopy);
end

% -------------------------------------------------------------------------
% Which grains are faceted?
% -------------------------------------------------------------------------
faceted_grain = false(1,Ngrain);

if isfield(PARAM,'aniso_phase') && ~isempty(PARAM.aniso_phase)

    for ig = 1:Ngrain
        iph = MODEL.phase_index(ig);
        faceted_grain(ig) = any(iph == PARAM.aniso_phase);
    end

elseif isfield(PARAM,'facet') && ~isempty(PARAM.facet)

    for ig = 1:Ngrain

        iph = MODEL.phase_index(ig);

        if iph <= numel(PARAM.facet) && ...
                isfield(PARAM.facet(iph),'mode') && ...
                ~isempty(PARAM.facet(iph).mode) && ...
                ~strcmpi(PARAM.facet(iph).mode,'iso')
            faceted_grain(ig) = true;
        end

    end
end

if isfield(PARAM,'aniso_grains') && ~isempty(PARAM.aniso_grains)

    if any(PARAM.aniso_grains < 1) || any(PARAM.aniso_grains > Ngrain)
        error('Calc_AC_Anisotropy_FacetedStiffness: invalid PARAM.aniso_grains.')
    end

    faceted_grain(:) = false;
    faceted_grain(PARAM.aniso_grains) = true;
end

% -------------------------------------------------------------------------
% Allocate outputs
% -------------------------------------------------------------------------
PARAM.L_AC  = L_base;
PARAM.Lm_AC = Lm_base;
PARAM.LK_AC = LK_base;

PARAM.sigma_energy_fac = ones(ny,nx,Ngrain);
PARAM.sigma_star_fac   = ones(ny,nx,Ngrain);
PARAM.aniso_theta      = zeros(ny,nx,Ngrain);
PARAM.aniso_factor     = ones(ny,nx,Ngrain);
PARAM.aniso_ifacet     = zeros(ny,nx,Ngrain);

sigma_fac_raw  = ones(ny,nx,Ngrain);
sigma_star_raw = ones(ny,nx,Ngrain);
interface_mask = false(ny,nx,Ngrain);

% -------------------------------------------------------------------------
% First pass: grain-wise surface-energy factor
% -------------------------------------------------------------------------
for alpha = 1:Ngrain

    phi = STATE.phi(:,:,alpha);

    [gx,gy] = Local_Grad_Reflex(phi,GRID.dx,GRID.dy);

    gnorm    = sqrt(gx.^2 + gy.^2);
    mask     = gnorm > grad_min;
    theta_lab = atan2(gy,gx);

    if faceted_grain(alpha)

        iph = MODEL.phase_index(alpha);

        [facet_theta,facet_A,sigma_ref,A_ref,q] = ...
            Local_Get_Facet_Data(PARAM,iph,nfold,q_default);

        theta_crystal = Local_WrapHalfPi(theta_lab - theta_grain(alpha));
        [dtheta,ifacet] = Local_Nearest_Facet_Angle(theta_crystal,facet_theta);

        A_use = facet_A(ifacet);
        den   = sin(dtheta).^2 + q^2*cos(dtheta).^2;

        % Kundin-type surface-energy factor.
        sigma_energy = sigma_ref .* (A_ref./A_use) .* sqrt(den);
        sigma_fac    = sigma_energy ./ max(sigma_ref*q,eps);

        % True Kundin stiffness retained as a diagnostic.
        sigma_star = sigma_ref .* (A_use./A_ref) .* q^2 ./ den.^(3/2);

        sigma_fac(~mask)  = 1;
        sigma_star(~mask) = 1;

    else

        dtheta     = zeros(ny,nx);
        ifacet     = zeros(ny,nx);
        sigma_fac  = ones(ny,nx);
        sigma_star = ones(ny,nx);

    end

    sigma_fac_raw(:,:,alpha)  = sigma_fac;
    sigma_star_raw(:,:,alpha) = sigma_star;
    interface_mask(:,:,alpha) = mask;

    PARAM.sigma_energy_fac(:,:,alpha) = sigma_fac;
    PARAM.sigma_star_fac(:,:,alpha)   = sigma_star;
    PARAM.aniso_theta(:,:,alpha)      = dtheta;
    PARAM.aniso_ifacet(:,:,alpha)     = ifacet;

end

% -------------------------------------------------------------------------
% Second pass: pair-effective factor
% -------------------------------------------------------------------------
for alpha = 1:Ngrain

    p_a   = STATE.p(:,:,alpha);
    s_sum = zeros(ny,nx);
    w_sum = zeros(ny,nx);

    for beta = 1:Ngrain

        if beta == alpha
            continue
        end

        p_b = STATE.p(:,:,beta);

        % Diffuse-interface pair weight.
        w = p_a .* p_b;

        % Sharp 0/1 maps may have zero p_a*p_b before the first AC step.
        if max(w(:)) <= p_cut
            w = double(interface_mask(:,:,alpha) & interface_mask(:,:,beta));
        end

        if max(w(:)) <= p_cut
            continue
        end

        iph_a = MODEL.phase_index(alpha);
        iph_b = MODEL.phase_index(beta);

        sig_a = sigma_fac_raw(:,:,alpha);
        sig_b = sigma_fac_raw(:,:,beta);

        if iph_a == iph_b

            s_ab = ones(ny,nx);

            if isfield(PARAM,'aniso_same_phase') && PARAM.aniso_same_phase == 1
                s_ab = 0.5*rsl*(sig_a + sig_b);
            end

        elseif faceted_grain(alpha) && ~faceted_grain(beta)

            s_ab = sig_a;

        elseif ~faceted_grain(alpha) && faceted_grain(beta)

            s_ab = sig_b;

        elseif faceted_grain(alpha) && faceted_grain(beta)

            s_ab = 0.5*rsl*(sig_a + sig_b);

        else

            s_ab = ones(ny,nx);

        end

        s_sum = s_sum + w .* s_ab;
        w_sum = w_sum + w;

    end

    s_eff = ones(ny,nx);
    mask_pair = w_sum > p_cut;
    s_eff(mask_pair) = s_sum(mask_pair)./w_sum(mask_pair);

    if normalize_s == 1

        mask_norm = mask_pair & isfinite(s_eff);

        if any(mask_norm(:))

            s_mean = mean(s_eff(mask_norm));

            if isfinite(s_mean) && s_mean > 0
                s_eff = s_eff./s_mean;
            end

        end
    end

    s_eff = min(max(s_eff,s_min),s_max);
    s_eff(~mask_pair) = 1;

    PARAM.aniso_factor(:,:,alpha) = s_eff;

    % Preserve heterogeneous base Lm/LK and apply anisotropy only once.
    PARAM.L_AC(:,:,alpha)  = L_base(:,:,alpha);
    PARAM.Lm_AC(:,:,alpha) = Lm_base(:,:,alpha) .* s_eff;
    PARAM.LK_AC(:,:,alpha) = LK_base(:,:,alpha) .* s_eff;

end

end


%% =========================================================================
% Local helpers
% =========================================================================
function F3 = Local_Resolve_Base(PARAM,preferred_name,fallback_name,Ngrain,ny,nx)

if isfield(PARAM,preferred_name) && ~isempty(PARAM.(preferred_name))
    A = PARAM.(preferred_name);
elseif isfield(PARAM,fallback_name) && ~isempty(PARAM.(fallback_name))
    A = PARAM.(fallback_name);
else
    error('Calc_AC_Anisotropy_FacetedStiffness: missing %s or %s.', ...
          preferred_name,fallback_name)
end

if isscalar(A)

    F3 = repmat(A,ny,nx,Ngrain);

elseif ndims(A) == 2 && isequal(size(A),[ny nx])

    F3 = repmat(A,1,1,Ngrain);

elseif ndims(A) == 3 && size(A,1) == ny && size(A,2) == nx && ...
        size(A,3) >= Ngrain

    F3 = A(:,:,1:Ngrain);

else

    error(['Calc_AC_Anisotropy_FacetedStiffness: field %s/%s has ', ...
           'an incompatible size.'],preferred_name,fallback_name)

end

end


function [gx,gy] = Local_Grad_Reflex(A,dx,dy)

[ny,nx] = size(A);

if nx == 1
    AL = A;
    AR = A;
else
    AL = A(:,[2,1:nx-1]);
    AR = A(:,[2:nx,nx-1]);
end

if ny == 1
    AU = A;
    AD = A;
else
    AU = A([2,1:ny-1],:);
    AD = A([2:ny,ny-1],:);
end

gx = (AR - AL)/(2*dx);
gy = (AD - AU)/(2*dy);

end


function [facet_theta,facet_A,sigma_ref,A_ref,q] = ...
    Local_Get_Facet_Data(PARAM,iph,nfold,q_default)

facet_theta = pi*(0:nfold-1)/nfold;
facet_A     = ones(size(facet_theta));
sigma_ref   = 1.0;
A_ref       = 1.0;
q           = q_default;

if ~isfield(PARAM,'facet') || numel(PARAM.facet) < iph
    return
end

facet = PARAM.facet(iph);

if isfield(facet,'theta') && ~isempty(facet.theta)
    facet_theta = facet.theta(:).';
elseif isfield(facet,'theta_deg') && ~isempty(facet.theta_deg)
    facet_theta = facet.theta_deg(:).'*pi/180;
end

if isfield(facet,'A') && ~isempty(facet.A)
    facet_A = facet.A(:).';
elseif isfield(facet,'A_weight') && ~isempty(facet.A_weight)
    facet_A = facet.A_weight(:).';
else
    facet_A = ones(size(facet_theta));
end

if isfield(facet,'sigma_ref') && ~isempty(facet.sigma_ref)
    sigma_ref = facet.sigma_ref;
end

if isfield(facet,'A_ref') && ~isempty(facet.A_ref)

    A_ref = facet.A_ref;

elseif isfield(facet,'hkl') && ~isempty(facet.hkl)

    i001 = Local_Find_HKL(facet.hkl,'001');

    if ~isempty(i001)
        A_ref = facet_A(i001);
    else
        A_ref = facet_A(1);
    end

elseif ~isempty(facet_A)

    A_ref = facet_A(1);

end

if isfield(facet,'q') && ~isempty(facet.q)
    q = facet.q;
end

if numel(facet_A) ~= numel(facet_theta)
    error('facet_A and facet_theta must have the same length.')
end

if any(facet_A <= 0)
    error('All facet A values must be positive.')
end

if A_ref <= 0 || sigma_ref <= 0 || q <= 0
    error('A_ref, sigma_ref and q must be positive.')
end

end


function idx = Local_Find_HKL(hkl,target)

idx = [];

for i = 1:numel(hkl)

    s = hkl{i};

    if isstring(s)
        s = char(s);
    end

    s = regexprep(s,'[{}()\[\]\s]','');

    if strcmpi(s,target)
        idx = i;
        return
    end

end

end


function [dtheta_best,ifacet_best] = Local_Nearest_Facet_Angle(theta,facet_theta)

[ny,nx] = size(theta);
Nfacet  = numel(facet_theta);

abs_best    = inf(ny,nx);
dtheta_best = zeros(ny,nx);
ifacet_best = ones(ny,nx);

for k = 1:Nfacet

    dtheta = Local_WrapHalfPi(theta - facet_theta(k));
    take   = abs(dtheta) < abs_best;

    dtheta_best(take) = dtheta(take);
    abs_best(take)    = abs(dtheta(take));
    ifacet_best(take) = k;

end

end


function a = Local_WrapHalfPi(a)

a = mod(a + pi/2,pi) - pi/2;

end
